# Generated by Django 5.0 on 2024-02-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('tags', models.JSONField()),
            ],
        ),
    ]
