# Generated by Django 5.0 on 2023-12-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('problem_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('tags', models.JSONField()),
            ],
        ),
    ]
