# Generated by Django 5.0 on 2024-02-09 13:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ratedProblems',
            field=models.JSONField(default=users.models.defaultList),
        ),
    ]
